// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: logs.proto

package logs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogeServiceClient is the client API for LogeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogeServiceClient interface {
	WriteLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResonse, error)
}

type logeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogeServiceClient(cc grpc.ClientConnInterface) LogeServiceClient {
	return &logeServiceClient{cc}
}

func (c *logeServiceClient) WriteLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResonse, error) {
	out := new(LogResonse)
	err := c.cc.Invoke(ctx, "/logs.LogeService/WriteLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogeServiceServer is the server API for LogeService service.
// All implementations must embed UnimplementedLogeServiceServer
// for forward compatibility
type LogeServiceServer interface {
	WriteLog(context.Context, *LogRequest) (*LogResonse, error)
	mustEmbedUnimplementedLogeServiceServer()
}

// UnimplementedLogeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogeServiceServer struct {
}

func (UnimplementedLogeServiceServer) WriteLog(context.Context, *LogRequest) (*LogResonse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteLog not implemented")
}
func (UnimplementedLogeServiceServer) mustEmbedUnimplementedLogeServiceServer() {}

// UnsafeLogeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogeServiceServer will
// result in compilation errors.
type UnsafeLogeServiceServer interface {
	mustEmbedUnimplementedLogeServiceServer()
}

func RegisterLogeServiceServer(s grpc.ServiceRegistrar, srv LogeServiceServer) {
	s.RegisterService(&LogeService_ServiceDesc, srv)
}

func _LogeService_WriteLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogeServiceServer).WriteLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logs.LogeService/WriteLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogeServiceServer).WriteLog(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogeService_ServiceDesc is the grpc.ServiceDesc for LogeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logs.LogeService",
	HandlerType: (*LogeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLog",
			Handler:    _LogeService_WriteLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
